version: '3.1'

services:

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: example
      MYSQL_PASSWORD: example
      MYSQL_DATABASE: db_demo
    ports:
      - 3306:3306
      
  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - 8080:8080